services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=your_db_url_here

  frontend:
    build: ./frontend
    ports:
      - "80:81"
    stdin_open: true # Keeps the terminal interactive
    depends_on:
      - backend

# Optional: Add a database service here later (Postgres/Redis)